<?php
// $Id$
/**
 * @file
 * Include PHP 4 date handling files on systems where native date and
 * timezone handling won't work. This module will create the functions
 * date_create(), date_offset_get(), etc. that will work in PHP 4.
 *
 * This module is not needed on systems using PHP 5.2+ and won't be needed once
 * Drupal requires PHP 5.2.
 */

include_once('./'. drupal_get_path('module', 'date_php4') .'/date_php4_lib.inc');