<?php
// $Id$

/**
  * Implementation of hook_install().
  */
function jquery_calendar_install() {
  //set a high weight so jquery_calendar is called after all other hook_form_alters which may add jquery_calendar to various forms
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'jquery_calendar'");
}

function jquery_calendar_update_1() {
  $ret = array();
  db_query("UPDATE {system} SET weight = 10 WHERE name = 'jquery_calendar'");
  return $ret;
}